"""full_db

Revision ID: a4f778b3e9d4
Revises: 
Create Date: 2025-12-27 13:57:41.788204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a4f778b3e9d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_consumers',
                    sa.Column('consumer_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('api_key', sa.String(length=255), nullable=False),
                    sa.Column('allowed_ips', sa.Text(), nullable=True),
                    sa.Column('allowed_endpoints', sa.JSON(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('consumer_id'),
                    sa.UniqueConstraint('api_key')
                    )
    op.create_table('currencies',
                    sa.Column('currency_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('symbol', sa.String(length=5), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('currency_id')
                    )
    op.create_table('exchange_rates',
                    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('base_currency', sa.String(length=5), nullable=False),
                    sa.Column('target_currency', sa.String(length=5), nullable=False),
                    sa.Column('rate_value', sa.DECIMAL(precision=18, scale=6), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('rate_id')
                    )
    op.create_table('external_services',
                    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('base_url', sa.String(length=255), nullable=True),
                    sa.Column('auth_type', sa.String(length=50), nullable=True),
                    sa.Column('api_key', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('service_id')
                    )
    op.create_table('linking_banks',
                    sa.Column('bank_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('code', sa.String(length=20), nullable=True),
                    sa.Column('country', sa.String(length=50), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('bank_id')
                    )
    op.create_table('permissions',
                    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('permission_id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('role_id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('phone_number', sa.String(length=20), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('password_hash', sa.String(length=255), nullable=False),
                    sa.Column('full_name', sa.String(length=150), nullable=False),
                    sa.Column('date_of_birth', sa.Date(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('daily_limit', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('monthly_limit', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('user_type', sa.String(length=20), nullable=False),
                    sa.Column('gender', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('blocked_reason', sa.String(), nullable=True),
                    sa.CheckConstraint("gender IN ('MALE','FEMALE')", name='ck_users_gender'),
                    sa.CheckConstraint("user_type IN ('CUSTOMER','STAFF','SYSTEM')", name='ck_users_user_type'),
                    sa.CheckConstraint('daily_limit >= 0', name='ck_users_daily_limit_non_negative'),
                    sa.CheckConstraint('monthly_limit >= 0', name='ck_users_monthly_limit_non_negative'),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_table('address',
                    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(length=30), nullable=True),
                    sa.Column('city', sa.String(length=20), nullable=True),
                    sa.Column('location', sa.String(length=30), nullable=False),
                    sa.Column('apartment', sa.String(length=20), nullable=True),

                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('address_id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_index('idx_address_user_id', 'address', ['user_id'], unique=False)
    op.create_index('idx_userID_city_country', 'address', ['user_id', 'city', 'country'], unique=False)
    op.create_table('api_access_logs',
                    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('endpoint', sa.String(length=255), nullable=False),
                    sa.Column('http_method', sa.String(length=10), nullable=False),
                    sa.Column('request_body', sa.JSON(), nullable=True),
                    sa.Column('response_status', sa.Integer(), nullable=True),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['consumer_id'], ['api_consumers.consumer_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('log_id')
                    )
    op.create_table('external_service_logs',
                    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('service_id', sa.Integer(), nullable=True),
                    sa.Column('endpoint', sa.String(length=255), nullable=True),
                    sa.Column('http_method', sa.String(length=10), nullable=True),
                    sa.Column('request_body', sa.JSON(), nullable=True),
                    sa.Column('response_status', sa.Integer(), nullable=True),
                    sa.Column('response_body', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['service_id'], ['external_services.service_id'], ),
                    sa.PrimaryKeyConstraint('log_id')
                    )
    op.create_table('favorite_contacts',
                    sa.Column('fc_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('phone_number', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('fc_id')
                    )
    op.create_table('favorite_internet',
                    sa.Column('fi_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=False),
                    sa.Column('subcription_number', sa.String(length=30), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('fi_id')
                    )
    op.create_table('favorite_transfers',
                    sa.Column('ft_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('wallet_number', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('ft_id')
                    )
    op.create_table('login_try',
                    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.Column('device_info', sa.String(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.CheckConstraint("status IN ('SUCCESS','FAILED')", name='ck_status'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('login_id')
                    )
    op.create_table('notifications',
                    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('notification_id')
                    )
    op.create_table('password_reset',
                    sa.Column('reset_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('changed_at', sa.DateTime(), nullable=False),
                    sa.Column('method', sa.String(length=50), nullable=False),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.CheckConstraint("method IN ('USER_CHANGE', 'FORGOT_PASSWORD', 'ADMIN_RESET')",
                                       name='ck_password_reset_method'),

                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('reset_id')
                    )
    op.create_table('role_permissions',
                    sa.Column('rp_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.Column('granted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
                    sa.PrimaryKeyConstraint('rp_id'),
                    sa.UniqueConstraint('role_id', 'permission_id', name='idx_rolID_permsionID')
                    )
    op.create_table('staff',
                    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('monthly_salary', sa.DECIMAL(10, 2), nullable=False),
                    sa.Column('hire_date', sa.Date(), nullable=False),
                    sa.Column('university_major', sa.String(length=100), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('staff_id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('transactions',
                    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('currency_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.DECIMAL(precision=11, scale=2), nullable=False),
                    sa.Column('fee', sa.DECIMAL(precision=9, scale=2), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED')", name='ck_transaction_status'),
                    sa.CheckConstraint(
                        "type IN ('INITIAL_FUNDING', 'TRANSFER', 'CASH_IN', 'CASH_DEPOSIT', 'MOBILE_TOPUP', "
                        "'ATM_WITHDRAW', 'EXCHANGE')",
                        name="ck_transaction_type"
                    ),
                    sa.CheckConstraint('amount >= 0', name='ck_transaction_amount'),
                    sa.ForeignKeyConstraint(['currency_id'], ['currencies.currency_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('transaction_id')
                    )
    op.create_index('idx_user_recent_transactions', 'transactions', ['user_id', 'created_at', 'status'], unique=False)
    op.create_table('user_devices',
                    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_type', sa.String(length=20), nullable=False),
                    sa.Column('device_name', sa.String(length=100), nullable=False),
                    sa.Column('device_type', sa.String(length=50), nullable=True),
                    sa.Column('os', sa.String(length=50), nullable=False),
                    sa.Column('browser', sa.String(length=50), nullable=True),
                    sa.Column('fingerprint', sa.String(length=255), nullable=True),
                    sa.Column('ip_address', sa.String(length=45), nullable=False),
                    sa.Column('location', sa.String(length=100), nullable=True),
                    sa.Column('jwt_token', sa.String(length=255), nullable=True),
                    sa.Column('last_used', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.CheckConstraint("user_type IN ('CUSTOMER','STAFF')", name='ck_devices_user_type'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('device_id')
                    )
    op.create_table('user_kyc',
                    sa.Column('kyc_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('id_type', sa.String(length=50), nullable=False),
                    sa.Column('id_number', sa.String(length=50), nullable=False),
                    sa.Column('id_front_image', sa.String(length=255), nullable=True),
                    sa.Column('id_back_image', sa.String(length=255), nullable=True),
                    sa.Column('selfie_image', sa.String(length=255), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('verified_by', sa.Integer(), nullable=True),
                    sa.Column('verified_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id_expiry', sa.Date(), nullable=False),
                    sa.Column('nationality', sa.String(length=50), nullable=False),
                    sa.Column('rejection_reason', sa.String(), nullable=True),
                    sa.CheckConstraint("id_type IN ('NATIONAL_ID','PASSPORT')", name='ck_id_type'),
                    sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')", name='ck_user_kyc_status'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('kyc_id'),
                    sa.UniqueConstraint('id_number'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('user_sessions',
                    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('device_info', sa.String(), nullable=True),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.Column('token', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('last_access', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('session_id')
                    )
    op.create_table('verifications',
                    sa.Column('verification_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('otp_code', sa.String(length=8), nullable=False),
                    sa.Column('otp_expiry', sa.DateTime(), nullable=False),
                    sa.Column('is_used', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('device_info', sa.String(), nullable=True),
                    sa.Column('verification_type', sa.String(length=25), nullable=False),
                    sa.Column('try_count', sa.Integer(), nullable=False),
                    sa.CheckConstraint("verification_type IN ('register','password_reset')", name='ck_verifi_type'),
                    sa.CheckConstraint('try_count >= 0', name='ck_verifications_try_count_non_negative'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('verification_id')
                    )
    op.create_index('idx_clean_expired_otp', 'verifications', ['user_id', 'is_used', 'otp_expiry'], unique=False)
    op.create_table('wallets',
                    sa.Column('wallet_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('wallet_number', sa.String(length=100), nullable=False),
                    sa.Column('is_system', sa.Boolean(), nullable=True),
                    sa.Column('status', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('closed_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')", name='ck_wallet_status'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('wallet_id'),
                    sa.UniqueConstraint('user_id'),
                    sa.UniqueConstraint('wallet_number')
                    )
    op.create_table('api_keys_update',
                    sa.Column('au_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('old_api_key', sa.String(length=255), nullable=False),
                    sa.Column('new_api_key', sa.String(length=255), nullable=False),
                    sa.Column('changed_by', sa.Integer(), nullable=False),
                    sa.Column('changed_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['changed_by'], ['staff.staff_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['consumer_id'], ['api_consumers.consumer_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('au_id')
                    )
    op.create_table('atm_withdraw_requests',
                    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('bank_id', sa.Integer(), nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=11), nullable=False),
                    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False),
                    sa.Column('currency', sa.Integer(), nullable=False),
                    sa.Column('pin_code', sa.String(length=10), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('transaction_ref', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED', 'EXPIRED')", name='ck_atm_status'),
                    sa.CheckConstraint('amount > 0', name='ck_atm_amount'),
                    sa.ForeignKeyConstraint(['bank_id'], ['linking_banks.bank_id'], ),
                    sa.ForeignKeyConstraint(['currency'], ['currencies.currency_id'], ),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('request_id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('transaction_id'),
                    sa.UniqueConstraint('transaction_ref')
                    )
    op.create_table('audit_logs',
                    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('changed_by', sa.Integer(), nullable=False),
                    sa.Column('action_type', sa.String(length=50), nullable=True),
                    sa.Column('old_data', sa.JSON(), nullable=True),
                    sa.Column('new_data', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['changed_by'], ['staff.staff_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('audit_id')
                    )
    op.create_table('call_center',
                    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.String(length=200), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('assigned_to', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['assigned_to'], ['staff.staff_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('ticket_id')
                    )
    op.create_table('fraud_reports',
                    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.String(length=100), nullable=False),
                    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('resolved_by', sa.Integer(), nullable=True),
                    sa.Column('resolved_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint("status IN ('PENDING', 'INVESTIGATING', 'RESOLVED')", name='ck_fraud_status'),
                    sa.ForeignKeyConstraint(['resolved_by'], ['staff.staff_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('report_id')
                    )
    op.create_table('staff_roles',
                    sa.Column('sr_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('staff_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('assigned_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('sr_id'),
                    sa.UniqueConstraint('staff_id', 'role_id', name='idx_stfID_rolID')
                    )
    op.create_table('system_settings',
                    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('setting_name', sa.String(length=100), nullable=False),
                    sa.Column('setting_value', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_public', sa.Boolean(), nullable=True),
                    sa.Column('updated_by', sa.Integer(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ),
                    sa.PrimaryKeyConstraint('setting_id'),
                    sa.UniqueConstraint('setting_name')
                    )
    op.create_table('transaction_exchange',
                    sa.Column('exchange_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('from_currency', sa.Integer(), nullable=False),
                    sa.Column('to_currency', sa.Integer(), nullable=False),
                    sa.Column('to_amount', sa.DECIMAL(precision=11, scale=2), nullable=False),
                    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=6), nullable=True),
                    sa.ForeignKeyConstraint(['from_currency'], ['currencies.currency_id'], ),
                    sa.ForeignKeyConstraint(['to_currency'], ['currencies.currency_id'], ),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('exchange_id'),
                    sa.UniqueConstraint('transaction_id')
                    )
    op.create_table('transaction_topups',
                    sa.Column('topup_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('phone_number', sa.String(length=15), nullable=False),
                    sa.Column('package_code', sa.String(length=20), nullable=True),
                    sa.Column('transaction_ref', sa.String(length=100), nullable=False),
                    sa.Column('status_details', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('topup_id'),
                    sa.UniqueConstraint('transaction_id'),
                    sa.UniqueConstraint('transaction_ref')
                    )
    op.create_table('transaction_transfers',
                    sa.Column('transfers_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('from_wallet', sa.Integer(), nullable=False),
                    sa.Column('to_wallet', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['from_wallet'], ['wallets.wallet_id'], ),
                    sa.ForeignKeyConstraint(['to_wallet'], ['wallets.wallet_id'], ),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('transfers_id'),
                    sa.UniqueConstraint('transaction_id')
                    )
    op.create_table('user_limits',
                    sa.Column('limit_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('old_limit', sa.DECIMAL(precision=9, scale=2), nullable=True),
                    sa.Column('new_limit', sa.DECIMAL(precision=9, scale=2), nullable=True),
                    sa.Column('type', sa.Text(), nullable=True),
                    sa.Column('changed_by', sa.Integer(), nullable=False),
                    sa.Column('changed_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint("type IN('daily_limit','monthly_limit')", name='type_limit'),
                    sa.ForeignKeyConstraint(['changed_by'], ['staff.staff_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('limit_id')
                    )
    op.create_table('wallet_accounts',
                    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('wallet_id', sa.Integer(), nullable=False),
                    sa.Column('currency_id', sa.Integer(), nullable=False),
                    sa.Column('balance', sa.DECIMAL(precision=11, scale=2), nullable=True),
                    sa.Column('status', sa.String(length=10), nullable=True),
                    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')", name='ck_account_status'),
                    sa.ForeignKeyConstraint(['currency_id'], ['currencies.currency_id'], ),
                    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ),
                    sa.PrimaryKeyConstraint('account_id'),
                    sa.UniqueConstraint('wallet_id', 'currency_id', name='idx_unique_wallet_currency')
                    )
    op.create_table('settings_update',
                    sa.Column('updateSett_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('setting_id', sa.Integer(), nullable=False),
                    sa.Column('old_value', sa.Text(), nullable=True),
                    sa.Column('new_value', sa.Text(), nullable=True),
                    sa.Column('changed_by', sa.Integer(), nullable=False),
                    sa.Column('changed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['changed_by'], ['staff.staff_id'], ),
                    sa.ForeignKeyConstraint(['setting_id'], ['system_settings.setting_id'], ),
                    sa.PrimaryKeyConstraint('updateSett_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_update')
    op.drop_table('wallet_accounts')
    op.drop_table('user_limits')
    op.drop_table('transaction_transfers')
    op.drop_table('transaction_topups')
    op.drop_table('transaction_exchange')
    op.drop_table('system_settings')
    op.drop_table('staff_roles')
    op.drop_table('fraud_reports')
    op.drop_table('call_center')
    op.drop_table('audit_logs')
    op.drop_table('atm_withdraw_requests')
    op.drop_table('api_keys_update')
    op.drop_table('wallets')
    op.drop_index('idx_clean_expired_otp', table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('user_sessions')
    op.drop_table('user_kyc')
    op.drop_table('user_devices')
    op.drop_index('idx_user_recent_transactions', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('staff')
    op.drop_table('role_permissions')
    op.drop_table('password_reset')
    op.drop_table('notifications')
    op.drop_table('login_try')
    op.drop_table('favorite_transfers')
    op.drop_table('favorite_internet')
    op.drop_table('favorite_contacts')
    op.drop_table('external_service_logs')
    op.drop_table('api_access_logs')
    op.drop_index('idx_userID_city_country', table_name='address')
    op.drop_index('idx_address_user_id', table_name='address')
    op.drop_table('address')
    op.drop_index('idx_users_phone_number', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('linking_banks')
    op.drop_table('external_services')
    op.drop_table('exchange_rates')
    op.drop_table('currencies')
    op.drop_table('api_consumers')
    # ### end Alembic commands ###
from alembic import op
import sqlalchemy as sa

# اضافة جديدة
def upgrades():
    op.create_table(
        "transaction_cash_deposits",
        sa.Column("cash_deposit_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("transaction_id", sa.Integer(), sa.ForeignKey("transactions.transaction_id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("staff_user_id", sa.Integer(), sa.ForeignKey("users.user_id"), nullable=False),
        sa.Column("wallet_id", sa.Integer(), sa.ForeignKey("wallets.wallet_id"), nullable=False),
        sa.Column("depositor_name", sa.String(length=150), nullable=True),
        sa.Column("depositor_phone", sa.String(length=20), nullable=True),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )


def downgrades():
    op.drop_table("transaction_cash_deposits")